name: fux
version: 0.0.0.0
category: Music
license: GPL-3.0
license-file: COPYING
synopsis: An experimental contrapuntal music generator.
description: Fux is an experimental, highly-WIP project aiming at the generation of contrapuntal music.

             For now, the project only has a WIP cantus firmus generator and some types with the expectation of being expanded in the future.
author: Heitor Toledo Lassarote de Paula
maintainer: Heitor Toledo Lassarote de Paula <heitortoledo@hotmail.com>
build-type: Simple

dependencies:
  - base

default-extensions:
  - BlockArguments
  - DataKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleInstances
  - FunctionalDependencies
  - ImportQualifiedPost
  - LambdaCase
  - LexicalNegation
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns
  - UndecidableInstances

library:
  source-dirs:
    - src/

  dependencies:
    - containers
    - logict
    - megaparsec
    - MonadRandom
    - mtl
    - parser-combinators
    - pretty
    - random
    - template-haskell
    - text
    - unicode

  ghc-options:
    - -Weverything
    - -Wno-all-missed-specializations
    - -Wno-implicit-prelude
    - -Wno-missing-import-lists
    - -Wno-missing-kind-signatures
    - -Wno-missing-safe-haskell-mode
    - -Wno-safe
    - -Wno-unsafe

tests:
  fux-core:
    main: Driver.hs

    source-dirs:
      - test/fux-core/

    dependencies:
      - fux
      - QuickCheck
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
